### ISSUE TITLE
BC66 I2C (BME280)

### ISSUE THREAD

**Issue by Redferne** [Wiz-IO/framework-quectel#1]
Using the Olimex Dev Kit (https://www.olimex.com/Products/IoT/NB-IoT/NB-IoT-DevKit/open-source-hardware). Attached a BME280 to the I2C0-SCL(RI) and I2C0-SDA(DCD) pins but can only read zeros from the I2C bus. Tried both address 0x76/0x77. Took a quick look with the logic analyzer and it seems that it's driving the bus at 400kHz (as expected). But it's decoding a NACK?

Using firmware BC66NBR01A04, is it worth testing BC66NBR01A07?
Any other ideas? Thanks!

![image](https://user-images.githubusercontent.com/2379821/67864639-35b69d00-fb26-11e9-9e35-613905090fb1.png)

**Comment by Wiz-IO** [comment]
Arduino ? OpenCPU?

**Comment by Redferne** [comment]
Yes! Works beatifully, thanks. I would argue that the Arduino Wire interface should be using 7bit (https://www.arduino.cc/en/reference/wire). Will you accept PR?

**Comment by Wiz-IO** [comment]
8 bits is from Mediatek system driver, I just follow Quectel SDK ...
what is PR?

**Comment by Wiz-IO** [comment]
Pool Request ? ... no problem...
if someone find some isues ...

**Comment by Redferne** [comment]
Pull Request (github patch). Will spend some hours on this devboard (Arduino framework) and see if I can make something cool. Will submit PRs. Thanks for your huge work on this! It is really amazing.

**Comment by Redferne** [comment]
PR merged :smile:
