### ISSUE TITLE
BC66 : How to know when UART TX has finished sending.

### ISSUE THREAD

**Issue by artofdestroy** [Wiz-IO/framework-quectel#10]
Are there any ways to know when UART TX has finished sending, 
like
`Serial.write(msg, sizeof(msg))`
`while (Serial.is_txbusy() == true); // <-- Like this`
`next_process()`
or some callback that will call when TX has finished sending.

For `Serial.flush()`(https://github.com/Wiz-IO/framework-quectel/blob/master/arduino/cores/bc66/HardwareSerial.h#L52), its flush all data waiting in RX buffer instead of waits for the transmission of outgoing serial data to complete just like Arduino ref said(https://www.arduino.cc/reference/en/language/functions/communication/serial/flush/).

**Comment by Wiz-IO** [comment]
No, kernel use DMA sending...
or ask Quectel - Arduino port use OpenCPU
