### ISSUE TITLE
Expand SRAM

### ISSUE THREAD

**Issue by KristoferKlein** [Wiz-IO/framework-quectel#12]
Hi
Is it possible to expand the SRAM for more than 256 bytes for the BC66?

example
RETSRAM (rwx) : ORIGIN = 0x???????, LENGTH = 512

**Comment by Wiz-IO** [comment]
The last used address from Quectel is:
.md_retsram_bss: **04301D80**                                         ; _md_retsram_data_end
version BC66NBR01A10

**Comment by KristoferKlein** [comment]
So, this should work then

RETSRAM (rwx) : ORIGIN = 0x04301E80, LENGTH = 512

**Comment by Wiz-IO** [comment]
RETSRAM (rwx) : ORIGIN = 0x04301E00, LENGTH = 512

RETSRAM end is 0x04301FFF

**Comment by KristoferKlein** [comment]
Ah, off course ;-)
Many thanks for the help
