### ISSUE TITLE
Question on BG96 SDK supported for arduino

### ISSUE THREAD

**Issue by xbvg** [Wiz-IO/framework-quectel#13]
Hi,

It's more a question than an issue. I could not find the information on which SDK of BG96 is supported for the arduino platformIO.

I tried the SDK 424 with platformIO threadX and the code is running fine but compiling instead with arduino, the code will not run. We had a similar problem in the past because we used to have SDK 2. Is all SDK compatible or only one version?

Thank you in advance!

**Comment by Wiz-IO** [comment]
Hi
Arduino work only with SDK 2
The firmwares for SDK 3 and 4 have MMU enabled and .... not work ... there is little diferences

**Comment by xbvg** [comment]
Thank you very much! Will try on SDK2.
