### ISSUE TITLE
Usage with Espressif platform for ESP32 using Arduino Framework

### ISSUE THREAD

**Issue by alexqzd** [Wiz-IO/framework-quectel#14]
I'm having a hard time figuring out how can I use this as a library to connect with an EC25 over UART using an ESP32 with Arduino framework. Some guidance would be really appreciated. Thanks.

**Comment by Wiz-IO** [comment]
Hi,

EC2x is a Linux module... this platform can compile normal linux/posix application ( executed inside module )
Ack your local Quectel support for all documents....
example: https://www.youtube.com/watch?v=sbLJNXTRLxc&ab_channel=GeorgiAngelov
_BTW: Arduino port is not shared yet..._

for ESP as master you can use any RIL ( AT commands ) Arduino library or
implement any open source RIL as
https://github.com/aosp-mirror/platform_hardware_ril/tree/master/reference-ril

**Comment by Wiz-IO** [comment]
and read this
https://github.com/Wiz-IO/platform-quectel/wiki/Framework-OpenLinux

**Comment by alexqzd** [comment]
Got it. Thanks!
